# Generated by Django 6.0.2 on 2026-02-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата поступления письма')),
                ('full_name', models.CharField(max_length=50, verbose_name='Фамилия, имя, отчество отправителя')),
                ('sender', models.CharField(max_length=50, verbose_name='Название предприятия или объекта, откуда поступило обращение')),
                ('tel_number', models.CharField(verbose_name='Контактный номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты отправителя')),
                ('factory_nums', models.CharField(max_length=50, verbose_name='Номера приборов (газонализаторов), указанные в письме')),
                ('device_type', models.CharField(max_length=50, verbose_name='Модель или тип устройства')),
                ('emotional_color', models.CharField(max_length=50, verbose_name='Анализ тональности (позитив/нейтраль/негатив)')),
                ('question', models.TextField(verbose_name='Краткое описание проблемы или запроса')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
